version: '3.8'

services:
  db:
    image: postgres:16
    container_name: lifetracker_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - lifetracker_db_data:/var/lib/postgresql/data
      