name: lint-and-test

on:
  push:
    branches: [main]
  pull_request:
    
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: astral-sh/setup-uv@v6
      - name: Sync dependencies
        run: |
          uv venv
          uv sync --dev
      - name: Ruff lint
        run: uv run ruff check src --output-format=github