name: style_check

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set-up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.12.0

      - name: Test style
        run: ruff check ./src
