name: style_check

on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v2
        with:
          virtualenvs-in-project: true

      - name: Cache virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install deps
        run: poetry install --no-interaction --no-root

      - name: Ruff lint
        run: poetry run ruff check src --output-format=github